# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    routing_loader: false
    format_listener:
        rules:
            - { path: '^/api', priorities: [ 'json'], fallback_format: json, prefer_extension: true }
    zone:
        - { path: ^/api/* }
    view:
        view_response_listener: 'force'
        formats:
            json: true